name: senior

on:
  push:

jobs:
  inflate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dare: ["move", "assume", "laboratory", "advocate", "sensible"]
        expand: ["forty", "reservation", "bounce", "guidance"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java --enable-native-access=ALL-UNNAMED -jar Kt.jar
